name: convenient_architecture
description: Collection of helper classes and methods.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.3
  fpdart: ^0.2.0
  meta: ^1.8.0

dev_dependencies:
  all_lint_rules_community: ^0.0.14
  lints: ^2.0.0
  test: ^1.16.0
